name: Get HTML from Web Page
on:
  workflow_dispatch:

jobs:
  get_html:
    runs-on: ubuntu-latest
    steps:
      - name: Get HTML
        run: |
          HTML_CONTENT=$(curl -v -s https://t.me/ZT_officiel)
          echo "HTML_CONTENT: $HTML_CONTENT"
        shell: bash