name: Get HTML from Web Page
on:
  push:
    branches:
      - main

jobs:
  get_html:
    runs-on: ubuntu-latest
    steps:
      - name: Get HTML
        run: |
          HTML_CONTENT=$(curl -v -s https://t.me/ZT_officiel)
          echo "HTML: $HTML_CONTENT"
      - name: Get Title
        run: |
          TITLE=$(echo "$HTML_CONTENT" | grep -oP '<div class="tgme_page_title"[^>]*><span dir="auto">([^<]+)</span></div>' | sed -n 's/.*<span dir="auto">\([^<]*\)<\/span><\/div>/\1/p')
          echo "Title: $TITLE"
        shell: bash
